### ISSUE TITLE
Please add how you are using the presenter class

### ISSUE THREAD

**Issue by Xavi007** [tlarsin/Android-Skeleton#1]
Hi Tristan

I was following your article on implementing RxJava and Retrofit [here](https://android.jlelse.eu/implementing-rxjava2-retrofit2-for-better-performance-during-api-calls-fe1c53e1f939). But you have not provided details on how to implement the Presenter class and then how to use it. A little sample code will work for me, I am mostly beginning in Android development and wonder if this follows MVP architecture

**Comment by tlarsin** [comment]
@Xavi007 Hey, thanks for reading my article! Are you wanting a code sample of MVP architecture? Model, View and Presenter class?
